language: python
python:
    - "2.7"
    - "3.5"

before_script:
  - psql -c 'create database inboxenTest;' -U postgres

install:
    - mkdir node_modules
    - travis_retry npm update
    - travis_retry pip install -q -U setuptools
    - travis_retry pip install -q -r requirements.txt
    - travis_retry pip install -q codecov
    - travis_retry gem install sass
    - python manage.py collectstatic --noinput --settings=inboxen.tests.settings

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
  allow_failures:
    - python: "3.5"

script:
    - coverage run --branch  manage.py test --settings=inboxen.tests.settings

after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG1vZ2dlcnM4NyUzQW1hdHJpeC5vcmcvJTIxZlRMa1dtaG9FWFRlUG1VaXhuJTNBbWF0cml4Lm9yZw"
        on_success: always
        on_failure: always
        on_start: never

sudo: false
